language: node_js
node_js:
    - "node"
before_script:
    - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
    - sudo /etc/init.d/postgresql restart
    - psql -U postgres -c 'CREATE DATABASE to_the_skies_template;'
    - psql to_the_skies_template < ./sql/template.sql
addons:
    apt:
        sources:
            - precise-pgdg-9.5
        packages:
            - postgresql-9.5
            - postgresql-contrib-9.5
    postgresql: 9.5
env:
    global:
        - PGPORT=5433
        - DB_PORT=5433
sudo: required
